openapi: 3.0.1
info:
  title: PetShop API
  description: |-
    API PetShop

  version: pet-1234567
paths:
  /pets:
    get:
      tags:
        - pets
      summary: List all pets
      operationId: listPets
      parameters:
        - name: number
          in: query
          description: Pet number
          required: true
          schema:
            type: integer
            format: int64
        - name: name
          in: query
          description: Pet name
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PetDto'

components:
  schemas:
    PetDto:
      type: object
      required:
        - id
        - name
        - payDate
        - dateEnd
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
        payDate:
          type: string
          description: Date and time of buy
          format: date-time
        dateBirthday:
          type: string
          description: Date of birthday
          format: date